[2025-07-22T17:47:03.928+0000] {processor.py:161} INFO - Started process (PID=649) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:47:03.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:47:03.931+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:47:03.930+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:47:04.246+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:47:04.244+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:47:04.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:47:04.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.330 seconds
[2025-07-22T17:47:34.653+0000] {processor.py:161} INFO - Started process (PID=709) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:47:34.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:47:34.655+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:47:34.655+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:47:34.952+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:47:34.947+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:47:34.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:47:34.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.313 seconds
[2025-07-22T17:48:05.564+0000] {processor.py:161} INFO - Started process (PID=769) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:48:05.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:48:05.567+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:48:05.567+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:48:05.864+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:48:05.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:48:05.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:48:05.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.315 seconds
[2025-07-22T17:48:36.457+0000] {processor.py:161} INFO - Started process (PID=829) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:48:36.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:48:36.459+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:48:36.459+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:48:36.743+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:48:36.741+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:48:36.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:48:36.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.304 seconds
[2025-07-22T17:49:06.782+0000] {processor.py:161} INFO - Started process (PID=894) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:49:06.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:49:06.783+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:49:06.783+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:49:07.074+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:49:07.073+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:49:07.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:49:07.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.300 seconds
[2025-07-22T17:49:37.975+0000] {processor.py:161} INFO - Started process (PID=958) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:49:37.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:49:37.979+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:49:37.978+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:49:38.341+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:49:38.340+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:49:38.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:49:38.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.380 seconds
[2025-07-22T17:50:09.318+0000] {processor.py:161} INFO - Started process (PID=1023) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:50:09.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:50:09.324+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:50:09.323+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:50:09.589+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:50:09.587+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:50:09.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:50:09.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.290 seconds
[2025-07-22T17:50:40.417+0000] {processor.py:161} INFO - Started process (PID=1083) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:50:40.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:50:40.423+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:50:40.423+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:50:40.974+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:50:40.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:50:40.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:50:40.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.585 seconds
[2025-07-22T17:51:11.130+0000] {processor.py:161} INFO - Started process (PID=1144) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:51:11.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:51:11.132+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:51:11.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:51:11.354+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:51:11.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:51:11.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:51:11.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.235 seconds
[2025-07-22T17:51:41.823+0000] {processor.py:161} INFO - Started process (PID=1203) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:51:41.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:51:41.827+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:51:41.827+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:51:42.032+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:51:42.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:51:42.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:51:42.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.222 seconds
[2025-07-22T17:52:12.916+0000] {processor.py:161} INFO - Started process (PID=1263) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:52:12.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:52:12.921+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:52:12.920+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:52:13.138+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:52:13.136+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:52:13.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:52:13.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.239 seconds
[2025-07-22T17:52:43.856+0000] {processor.py:161} INFO - Started process (PID=1323) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:52:43.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:52:43.858+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:52:43.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:52:44.164+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:52:44.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:52:44.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:52:44.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.324 seconds
[2025-07-22T17:53:15.069+0000] {processor.py:161} INFO - Started process (PID=1383) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:53:15.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:53:15.072+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:53:15.072+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:53:15.278+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:53:15.277+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:53:15.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:53:15.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.224 seconds
[2025-07-22T17:53:46.167+0000] {processor.py:161} INFO - Started process (PID=1443) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:53:46.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:53:46.169+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:53:46.169+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:53:46.350+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:53:46.348+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:53:46.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:53:46.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.200 seconds
[2025-07-22T17:54:16.498+0000] {processor.py:161} INFO - Started process (PID=1503) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:54:16.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:54:16.502+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:54:16.501+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:54:16.684+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:54:16.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:54:16.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:54:16.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.205 seconds
[2025-07-22T17:54:47.314+0000] {processor.py:161} INFO - Started process (PID=1563) to work on /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:54:47.316+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/etl_pipeline_dag.py for tasks to queue
[2025-07-22T17:54:47.319+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:54:47.318+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:54:47.499+0000] {logging_mixin.py:188} INFO - [2025-07-22T17:54:47.498+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_dag.py", line 12, in <module>
    from src.etl.csv_data_loader import load_csv
ModuleNotFoundError: No module named 'src'
[2025-07-22T17:54:47.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_dag.py
[2025-07-22T17:54:47.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/etl_pipeline_dag.py took 0.199 seconds
